server:
  port: 7845
spring:
  application:
    name: ReAIoT
  ai:
    openai: # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
      api-key: "${DEEPSEEK_API_KEY}"
      base-url: "${DEEPSEEK_BASE_URL:https://api.deepseek.com}" # 深度求索
      chat:
        options:
          model: "${DEEPSEEK_MODEL:deepseek-chat}" # deepseek-chat 或 deepseek-reasoner
  #  r2dbc:
  #    url: "${R2DBC_URL:r2dbc:postgresql://113.31.103.66:5432/thingsboard}"
  #    username: "${R2DBC_USERNAME:postgres}"
  #    password: "${R2DBC_PASSWORD:3.1415926Pi}"
  #  sql:
  #    init:
  #      mode: always
  data:
    cassandra:
      keyspace-name: "${CASSANDRA_KEYSPACE_NAME:reaiot_cmp}"
      contact-points: "${CASSANDRA_URL:10.0.0.66:9042}"
      username: "${CASSANDRA_USERNAME:cassandra}"
      password: "${CASSANDRA_PASSWORD:cassandra}"
      local-datacenter: "${CASSANDRA_LOCAL_DATACENTER:datacenter1}"
logging:
  level:
    cn:
      easttrans:
        reaiot: TRACE
    io:
      netty:
        handler: TRACE
    reactor:
      netty:
        channel: TRACE