server:
  port: 7845

logging:
  level:
    cn:
      easttrans:
        reaiot: TRACE

spring:
  application:
    name: ReAIoT
  ai:
    openai: # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
      api-key: "${DEEPSEEK_API_KEY}"
      base-url: "${DEEPSEEK_BASE_URL:https://api.deepseek.com}" # 深度求索
      chat:
        options:
          model: "${DEEPSEEK_MODEL:deepseek-chat}" # deepseek-chat 或 deepseek-reasoner
