server:
  port: "${HTTP_PORT:7845}"

spring:
  application:
    name: ReAIoT Agentic
    title: Agentic Artificial Intelligence built on DeepSeek
  ai:
    embedding:
      transformer:
        cache:
          enabled: true
          directory: "${EMBEDDING_TRANSFORMER_DIR:/tmp/onnx-zoo}"
        onnx:
          modelUri: "${ONNX_URL:classpath:/onnx/all-MiniLM-L6-v2/model.onnx}" # https://hf-mirror.com/intfloat/e5-small-v2/resolve/main/model.onnx
        tokenizer:
          uri: "${TOKENIZER_URL:classpath:/onnx/all-MiniLM-L6-v2/tokenizer.json}" # https://hf-mirror.com/intfloat/e5-small-v2/raw/main/tokenizer.json
          options:
            padding: true
    openai: # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
      api-key: "${DEEPSEEK_API_KEY}"
      base-url: "${DEEPSEEK_BASE_URL:https://api.deepseek.com}" # 深度求索 https://api.deepseek.com 或 硅基流动 https://api.siliconflow.cn
      chat:
        options:
          model: "${DEEPSEEK_MODEL:deepseek-chat}" # deepseek-chat 或 deepseek-reasoner 或 deepseek-ai/DeepSeek-V3 或 deepseek-ai/DeepSeek-R1
          temperature: 0.6 # https://x.com/deepseek_ai/status/1890324295181824107
    chat:
      memory:
        cassandra:
          keyspace: "${CASSANDRA_KEY_SPACE:reaiot_5853}"
    vectorstore:
      cassandra:
        keyspace: "${CASSANDRA_KEY_SPACE:reaiot_5853}"
        table: ai_vector_store
        initialize-schema: true
  cassandra:
    cluster-name: ReAIoT
    #    keyspace-name: "${CASSANDRA_KEY_SPACE:reaiot_5853}"
    contact-points: "${EASTTRANS_CASSANDRA:10.0.0.66:9042,10.0.0.68:9042}" # 10.0.0.66, 10.0.0.68, 172.16.0.104, 172.16.0.106
    username: "${CASSANDRA_USERNAME:cassandra}"
    password: "${CASSANDRA_PASSWORD:cassandra}"
    local-datacenter: "${CASSANDRA_LOCAL_DATACENTER:datacenter1}"