server:
  port: 7845

spring:
  application:
    name: ReAIoT Agentic
    title: Agentic Artificial Intelligence built on DeepSeek
  ai:
    embedding:
      transformer:
        onnx:
          modelUri: https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
        tokenizer:
          uri: https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json
    openai: # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
      api-key: "${DEEPSEEK_API_KEY}"
      base-url: "${DEEPSEEK_BASE_URL:https://api.deepseek.com}" # 深度求索
      chat:
        options:
          model: "${DEEPSEEK_MODEL:deepseek-chat}" # deepseek-chat 或 deepseek-reasoner

easttrans:
  # 梁场
  beam-construction:
    base-url: "${BEAM_CONSTRUCTION_BASE_URL:http://172.16.0.94:8081/pro_api}" # https://nylc.jszhnl.com/pro_api
    username: "${BEAM_CONSTRUCTION_USERNAME}"
    password: "${BEAM_CONSTRUCTION_PASSWORD}"
    suffix: "${BEAM_CONSTRUCTION_SUFFIX:login_njlc}"
