server:
  port: 7845

spring:
  application:
    name: ReAIoT Agentic
    title: Agentic Artificial Intelligence built on DeepSeek
  ai:
    #    embedding:
    #      transformer:
    #        onnx:
    #          modelUri: "${ONNX_URL:https://hf-mirror.com/intfloat/e5-small-v2/resolve/main/model.onnx}"
    #        tokenizer:
    #          uri: "${TOKENIZER_URL:https://hf-mirror.com/intfloat/e5-small-v2/raw/main/tokenizer.json}"
    openai: # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
      api-key: "${DEEPSEEK_API_KEY}"
      base-url: "${DEEPSEEK_BASE_URL:https://api.deepseek.com}" # 深度求索 https://api.deepseek.com 或 硅基流动 https://api.siliconflow.cn
      chat:
        options:
          model: "${DEEPSEEK_MODEL:deepseek-chat}" # deepseek-chat 或 deepseek-reasoner 或 deepseek-ai/DeepSeek-V3 或 deepseek-ai/DeepSeek-R1
          temperature: 0.6
easttrans:
  # 梁场
  beam-construction:
    base-url: "${BEAM_CONSTRUCTION_BASE_URL:http://172.16.0.94:8081/pro_api}" # https://nylc.jszhnl.com/pro_api
    username: "${BEAM_CONSTRUCTION_USERNAME}"
    password: "${BEAM_CONSTRUCTION_PASSWORD}"
    suffix: "${BEAM_CONSTRUCTION_SUFFIX:login_njlc}"
  cassandra:
    contact-point: "${EASTTRANS_CASSANDRA:172.16.0.106}" # 10.0.0.66, 10.0.0.68, 172.16.0.104
    key-space: "${CASSANDRA_KEY_SPACE:reaiot_5853}"