### 物料入库
POST {{baseUrl}}/beamMtl/mtlStoragePage
Content-Type: application/json;charset=UTF-8
Authorization: {{token}}
Projectid: 5853

{
  "mtlName": "",
  "pageNum": 1,
  "pageSize": 10,
  "specificationMode": "",
  "total": 0
}


### 获取物料名称，规格型号
GET {{baseUrl}}/beamCode/codeTree?types=WLMC,GGXH
Authorization: {{token}}
Projectid: 5853

